### ISSUE TITLE
Contents of store are printed on failure

### ISSUE THREAD

**Issue by ashwin153** [gregfitch/pytest-securestore#5]
- Relates to https://github.com/pytest-dev/pytest/discussions/8910.
- Instead of returning the contents of `secrets.yaml`, consider returning an object that is functionally the same but has a modified `__repr__` and `__str__` that redact the contents of the store when it is printed by pytest.

**Comment by gregfitch** [comment]
https://github.com/gregfitch/pytest-securestore/pull/6
